spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/JDBCSpringSecurity?createDatabaseIfNotExist=true
    username: root
    password:


  jpa:
   show-sql: true
   properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: create-drop

server:
  port: 8085
